name       : pytorch
version    : 1.3.1
release    : 5
source     :
    - git|https://github.com/pytorch/pytorch : v1.3.1
license    : BSD-3-Clause
component  :
    - programming.python
    - ^libtorch : programming.library
summary    :
    - Tensors and Dynamic neural networks in Python with strong GPU acceleration
    - ^libtorch : PyTorch C++ API
description: |
    PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
patterns   :
    - ^libtorch :
        - /usr/include
        - /usr/lib64
optimize   :
    - speed
avx2       : yes
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(gflags)
    - pkgconfig(libavcodec)
    - pkgconfig(libglog)
    - pkgconfig(libzmq)
    - pkgconfig(ompi)
    - pkgconfig(openblas)
    - pkgconfig(opencv)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - leveldb-devel
    - lmdb-devel
    - numpy
    - pybind11
    - python-typing
    - pyyaml
    - snappy-devel
rundeps    :
    - numpy
    - python-cffi
    - pyyaml
    - ^libtorch :
        - pybind11
replaces   :
    - ^libtorch :
        - pytorch-devel
build      : |
    %python3_setup --cmake-only
    pushd ../py3build
    %cmake build \
        -DCMAKE_INSTALL_PREFIX=$PWD/torch \
        -DBLAS=OpenBLAS \
        -DBUILD_BINARY=ON \
        -DBUILD_CUSTOM_PROTOBUF=OFF \
        -DBUILD_TEST=OFF \
        -DUSE_FFMPEG=ON -DUSE_LEVELDB=ON \
        -DUSE_LMDB=ON \
        -DUSE_MKLDNN=OFF \
        -DUSE_OPENCV=ON \
        -DUSE_GFLAGS=ON \
        -DUSE_GLOG=ON \
        -DUSE_SYSTEM_EIGEN_INSTALL=ON \
        -DUSE_ZMQ=ON
    python3 setup.py build
    popd
install    : |
    %python3_install

    # Configure libtorch
    install -dm00755 $installdir/%libdir%
    TORCH_PATH=$(python3 -c "import site; print(site.getsitepackages()[0])")/torch
    mv $installdir/$TORCH_PATH/lib/* $installdir/%libdir%

    if [ ! -z "${AVX2BUILD}" ]; then
        rm -rf $installdir/usr/lib/python*
    else
        install -dm00755 $installdir/usr/include $installdir/%libdir%/cmake
        mv $installdir/$TORCH_PATH/include/* $installdir/usr/include
        rm -rf $installdir/usr/include/pybind11
        mv $installdir/$TORCH_PATH/share/cmake/* $installdir/%libdir%/cmake
        rm -rf $installdir/$TORCH_PATH/{include,lib,share/cmake}
        ln -sv /usr/include $installdir/$TORCH_PATH/include
        ln -sv %libdir% $installdir/$TORCH_PATH/lib
        ln -sv %libdir%/cmake $installdir/$TORCH_PATH/share/cmake
    fi
