name       : pytorch
version    : 1.0.1
release    : 1
source     :
    - git|https://github.com/pytorch/pytorch : v1.0.1
license    : BSD-3-Clause
component  : programming.python
summary    : Tensors and Dynamic neural networks in Python with strong GPU acceleration
description: |
    PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(gflags)
    - pkgconfig(libavcodec)
    - pkgconfig(libglog)
    - pkgconfig(libzmq)
    - pkgconfig(ompi)
    - pkgconfig(openblas)
    - pkgconfig(opencv)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - leveldb-devel
    - lmdb-devel
    - numpy
    - python-typing
    - pyyaml
    - snappy-devel
rundeps    :
    - numpy
    - python-cffi
    - pyyaml
build      : |
    export BUILD_BINARY=1
    export USE_FFMPEG=1
    export USE_LEVELDB=1
    export USE_LMDB=1
    export USE_OPENCV=1
    export EXTRA_CAFFE2_CMAKE_FLAGS="-DBLAS=OpenBLAS
                                     -DBUILD_CUSTOM_PROTOBUF=OFF
                                     -DUSE_GFLAGS=ON
                                     -DUSE_GLOG=ON
                                     -DUSE_OPENMP=ON
                                     -DUSE_SYSTEM_EIGEN_INSTALL=ON
                                     -DUSE_ZMQ=ON"

    # Force to use system protobuf
    rm -rfv third_party/protobuf

    %python3_setup
install    : |
    %python3_install --skip-build
