name       : pytorch
version    : 1.3.0
release    : 3
source     :
    - git|https://github.com/pytorch/pytorch : v1.3.0
license    : BSD-3-Clause
component  :
    - programming.python
summary    :
    - Tensors and Dynamic neural networks in Python with strong GPU acceleration
    - devel : PyTorch C++ API
description: |
    PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
patterns   :
    - devel :
        - /usr/lib64 # Install /usr/lib64/lib*.so.* to the devel subpackage
optimize   :
    - speed
builddeps  :
    - pkgconfig(eigen3)
    - pkgconfig(gflags)
    - pkgconfig(libavcodec)
    - pkgconfig(libglog)
    - pkgconfig(libzmq)
    - pkgconfig(ompi)
    - pkgconfig(openblas)
    - pkgconfig(opencv)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - leveldb-devel
    - lmdb-devel
    - numpy
    - python-typing
    - pyyaml
    - snappy-devel
rundeps    :
    - numpy
    - python-cffi
    - pyyaml
build      : |
    %python3_setup --cmake-only
    pushd ../py3build
    %cmake build \
        -DCMAKE_INSTALL_PREFIX=$PWD/torch \
        -DBLAS=OpenBLAS \
        -DBUILD_BINARY=ON \
        -DBUILD_CUSTOM_PROTOBUF=OFF \
        -DUSE_FFMPEG=ON -DUSE_LEVELDB=ON \
        -DUSE_LMDB=ON \
        -DUSE_MKLDNN=OFF \
        -DUSE_OPENCV=ON \
        -DUSE_GFLAGS=ON \
        -DUSE_GLOG=ON \
        -DUSE_SYSTEM_EIGEN_INSTALL=ON \
        -DUSE_ZMQ=ON
    python3 setup.py build
    popd
install    : |
    %python3_install

    install -dm00755 $installdir/usr/bin $installdir/usr/include $installdir/%libdir%/cmake
    TORCH_PATH=$(python3 -c "import site; print(site.getsitepackages()[0])")/torch
    for f in $installdir/$TORCH_PATH/bin/*; do
        ln -sv $TORCH_PATH/bin/`basename $f` $installdir/usr/bin
    done
    # Configure libtorch
    for f in $installdir/$TORCH_PATH/share/cmake/*; do
        ln -sv $TORCH_PATH/share/cmake/`basename $f` $installdir/%libdir%/cmake
    done
    for f in $installdir/$TORCH_PATH/include/*; do
        ln -sv $TORCH_PATH/include/`basename $f` $installdir/usr/include
    done
    for f in $installdir/$TORCH_PATH/lib/lib*.so*; do
        ln -sv $TORCH_PATH/lib/`basename $f` $installdir/%libdir%
    done
